config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :artists do
    resources :shows, only: [ :new, :create ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "artists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :shows
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :artist
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!

  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @shows = @artist.shows
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new, :unprocessable_entity
    end
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])

    if @artist.update(artist_params)
      redirect to @artist
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def artist_params
      params.require(:artist).permit(:name, :country)
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_artist

  def new
    @show = @artist.shows.new
  end

  def create
    @show = @artist.shows.build(show_params)

    if @show.save
      redirect_to @artist
    else
      render :new
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def show_params
      params.require(:show).permit(:venue, :city, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/artists/_form.html.erb
<%= form_with model: artist do |form| %>
  <div>
    <%= form.label :name %>

    <br>

    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :country %>

    <br>

    <%= form.text_field :country %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<ul>
  <li>
    <strong>
      Current name:
    </strong>
    <%= @artist.name %>
  </li>
  <li>
    <strong>
      Current country:
    </strong>
    <%= @artist.country %>
  </li>
</ul>

<%= render "form", artist: @artist %>

app/views/artists/index.html.erb
<h1>Artists</h1>

<ul>
  <% @artists.each do |artist| %>
    <li>
      <%= link_to artist.name, artist %>
    </li>
  <% end %>
</ul>

<%= link_to "Add Artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render "form", artist: @artist %>

app/views/artists/show.html.erb
<h1>
  <%= @artist.name %>
</h1>
<ul>
  <li>
    <b>Country:</b>
    <%= @artist.country %>
  </li>
</ul>

<h2>Upcoming shows</h2>
<ul>
  <% if @shows.empty? %>
  <li>
    Nothing here yet!
  </li>
  <% else %>
    <% @shows.each do |show| %>
      <li>
        <%= @artist.name.upcase %> @ <%= show.city %>, <%= show.venue %> | <%= show.date %>
    <% end %>
  <% end %>
</ul>

Know something we don't?

<%= link_to "Add show", new_artist_show_path(@artist) %>

<br>
<br>

<%= link_to "Edit Artist", edit_artist_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Beenat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= link_to "Home", "/"%>
    <%= yield %>
    <footer>
      <br>
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "Log in", new_user_session_path %>
        <%= link_to "Sign up", new_user_registration_path %>
      <% end %>
    </footer>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with model: [@artist, @show] do |form| %>
  <div>
    <%= form.label :venue %>

    <br>

    <%= form.text_field :venue %>

    <br>

    <%= form.label :city %>

    <br>
    <%= form.text_field :city %>
  </div>
  <br>
  <div>
    <%= form.label :date %>
    <%= form.date_field :date %>
    <br>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/new.html.erb
<h1>New show for <%= @artist.name %></h1>

<%= render "form", show: @show %>